Update config

diff --git a/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-history b/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-history
--- a/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-history
+++ b/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-history
@@ -1,8 +1,39 @@
-def runDocker(String dbEnv, String dbName, boolean showOnlyTag, String filterTagVersion) {
+def copyData() {
+  sh "mkdir -p $WORKSPACE/output"
+  sh 'cp -rf /var/jenkins_home/db/. $WORKSPACE/src'
+}
+
+def dockerRemove() {
+  echo '::: Remove image ************************************************************'
+  
+  // remove image
+  sh """        
+  # > /dev/null 2>&1 = Discards both the standard output and standard error of a command
+  # docker rmi database-changelog:1.0 > /dev/null 2>&1 && echo "image removed" || true
+
+  # 2>/dev/null = Discard standard error of a command
+  docker rmi database-changelog:1.0 2>/dev/null && echo "image removed" || { echo "image not found"; true; }
+  """
+}
+
+def dockerBuild() {
+  echo '::: Build image ************************************************************'
+  
+  // run shell script for building an image
+  sh '''
+  cp -r /dockerfiles/. $WORKSPACE/dockerfiles
+
+  cd dockerfiles/build
+  
+  ./build-database-changelog.sh
+
+  cd $WORKSPACE
+  '''
+}
+
+def runDocker(String command, String dbEnv, String dbName, boolean showOnlyTag, String filterTagVersion) {
 
   echo ">>>> $dbEnv"
-
-  def command = "history"
 
   def argsName1 = ""
   def argsValue1 = ""
@@ -38,7 +69,7 @@ pipeline {
   }
   parameters {
     choice(name: 'DB_ENV', choices:['SIT', 'UAT'])
-    string(name: 'DATABASE_NAME', defaultValue: 'database_b', description: 'Specific the database name\nr.g., database_b')
+    string(name: 'DATABASE_NAME', defaultValue: 'database_b', description: 'Specific the database name\ne.g., database_b')
     // choice(name: 'TYPE', choices:['DDL', 'DML', 'SP'], description: 'DDL - Data Definition Language\nDML - Data Manipulation Language\nSP - Stored Procedure')
     booleanParam(name: 'SHOW_ONLY_TAGS', defaultValue: false, description: 'Only shows tagged changeset list')
     string(name: 'FILTER_TAG_VERSION', defaultValue: '', description: 'To show a specific tag (Used when SHOW_ONLY_TAGS is checked)\ne.g., 1.0.0\ne.g., release_1.0\n*** Empty this field to show all tag list that tagged in database')
@@ -58,11 +89,11 @@ pipeline {
             echo "This is not a valid database name"
             error("Database name is not valid")
           }
-
-          // if(params.SHOW_ONLY_TAGS && params.FILTER_TAG_VERSION.isEmpty()) {
-          //   error("FILTER_TAG_VERSION parameter is not valid")
-          // }
         }
+
+        copyData()
+        dockerRemove()
+        dockerBuild()
 
       }
     }
@@ -70,33 +101,8 @@ pipeline {
       steps {
         echo '::: Generate history ************************************************************'
 
-        sh "mkdir -p $WORKSPACE/output"
-        sh 'cp -rf /var/jenkins_home/db/. $WORKSPACE/src'        
-
-        echo '::: Remove image ************************************************************'
-        // remove image
-        sh """        
-        # > /dev/null 2>&1 = Discards both the standard output and standard error of a command
-        # docker rmi database-changelog:1.0 > /dev/null 2>&1 && echo "image removed" || true
-
-        # 2>/dev/null = Discard standard error of a command
-        docker rmi database-changelog:1.0 2>/dev/null && echo "image removed" || { echo "image not found"; true; }
-        """
-
-        echo '::: Build image ************************************************************'
-        // run shell script for building an image
-        sh '''
-        cp -r /dockerfiles/. $WORKSPACE/dockerfiles
-
-        cd dockerfiles/build
-        
-        ./build-database-changelog.sh
-
-        cd $WORKSPACE
-        '''
-
         echo '::: Call runDocker() ************************************************************'
-        runDocker(params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.SHOW_ONLY_TAGS, params.FILTER_TAG_VERSION)
+        runDocker("history", params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.SHOW_ONLY_TAGS, params.FILTER_TAG_VERSION)
         echo '::: ============================================================================='
       }
     }
diff --git a/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-rollback-count b/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-rollback-count
--- a/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-rollback-count
+++ b/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-rollback-count
@@ -1,13 +1,40 @@
-def runDocker(String dbEnv, String dbName, boolean dryRun, String rollbackCount, String labels) {
+def copyData() {
+  sh "mkdir -p $WORKSPACE/output"
+  sh 'cp -rf /var/jenkins_home/db/. $WORKSPACE/src'
+}
+
+def dockerRemove() {
+  echo '::: Remove image ************************************************************'
+  
+  // remove image
+  sh """        
+  # > /dev/null 2>&1 = Discards both the standard output and standard error of a command
+  # docker rmi database-changelog:1.0 > /dev/null 2>&1 && echo "image removed" || true
+
+  # 2>/dev/null = Discard standard error of a command
+  docker rmi database-changelog:1.0 2>/dev/null && echo "image removed" || { echo "image not found"; true; }
+  """
+}
+
+def dockerBuild() {
+  echo '::: Build image ************************************************************'
+  
+  // run shell script for building an image
+  sh '''
+  cp -r /dockerfiles/. $WORKSPACE/dockerfiles
+
+  cd dockerfiles/build
+  
+  ./build-database-changelog.sh
+
+  cd $WORKSPACE
+  '''
+}
+
+def runDocker(String command, String dbEnv, String dbName, boolean dryRun, String rollbackCount, String labels) {
 
   echo "dbEnv >>>> [$dbEnv]"
   echo "dbName >>>> [$dbName]"
-
-  def command = "rollback-count"
-
-  if(dryRun) {
-    command = "rollback-count-dryrun"
-  }
 
   def argsName1 = "--count"
   def argsValue1 = "$rollbackCount"
@@ -38,9 +65,7 @@ pipeline {
   }
   parameters {
     choice(name: 'DB_ENV', choices:['SIT', 'UAT'])
-    string(name: 'DATABASE_NAME', defaultValue: 'database_b', description: 'Specific the database name\nr.g., database_b')
-    // string(name: 'PROJECT_NAME', defaultValue: 'sp_test', description: 'Specific the project name that you want to update\ne.g., <project-name>')
-    // choice(name: 'TYPE', choices:['DDL', 'DML', 'SP'], description: 'DDL - Data Definition Language\nDML - Data Manipulation Language\nSP - Stored Procedure')
+    string(name: 'DATABASE_NAME', defaultValue: 'database_b', description: 'Specific the database name\ne.g., database_b')
     booleanParam(name: 'DRY_RUN', defaultValue: true, description: 'Preview sql script before running migration')
     string(name: 'ROLLBACK_COUNT', defaultValue: '1', description: 'Number of changeset rollback')
     string(name: 'CHANGESET_LABEL', defaultValue: '', description: 'Changeset label,\n e.g., card-123 \n e.g., card-123 AND card-123-01 (for multiple labels)')
@@ -62,39 +87,37 @@ pipeline {
           }
         }
 
+        copyData()
+        dockerRemove()
+        dockerBuild()
+
       }
     }
-    stage('Rollback count') {
+    stage('Dry run') {
+      when {
+        expression {
+          params.DRY_RUN == true
+        }
+      }
+      steps {
+        sh 'echo "Dry run"'
+
+        echo '::: Call runDocker() ************************************************************'
+        runDocker("rollback-count-dryrun", params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.DRY_RUN, params.ROLLBACK_COUNT, params.CHANGESET_LABEL)
+        echo '::: ============================================================================='
+      }
+    }
+    stage('Rollback by count') {
+      when {
+        expression {
+          params.DRY_RUN == false
+        }
+      }
       steps {
         echo '::: Rollback count ************************************************************'
 
-        sh "mkdir -p $WORKSPACE/output"
-        sh 'cp -rf /var/jenkins_home/db/. $WORKSPACE/src'        
-
-        echo '::: Remove image ************************************************************'
-        // remove image
-        sh """        
-        # > /dev/null 2>&1 = Discards both the standard output and standard error of a command
-        # docker rmi database-changelog:1.0 > /dev/null 2>&1 && echo "image removed" || true
-
-        # 2>/dev/null = Discard standard error of a command
-        docker rmi database-changelog:1.0 2>/dev/null && echo "image removed" || { echo "image not found"; true; }
-        """
-
-        echo '::: Build image ************************************************************'
-        // run shell script for building an image
-        sh '''
-        cp -r /dockerfiles/. $WORKSPACE/dockerfiles
-
-        cd dockerfiles/build
-        
-        ./build-database-changelog.sh
-
-        cd $WORKSPACE
-        '''
-
         echo '::: Call runDocker() ************************************************************'
-        runDocker(params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.DRY_RUN, params.ROLLBACK_COUNT, params.CHANGESET_LABEL)
+        runDocker("rollback-count", params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.DRY_RUN, params.ROLLBACK_COUNT, params.CHANGESET_LABEL)
         echo '::: ============================================================================='
       }
     }
diff --git a/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-rollback-tag b/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-rollback-tag
--- a/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-rollback-tag
+++ b/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-rollback-tag
@@ -1,12 +1,39 @@
-def runDocker(String dbEnv, String dbName, boolean dryRun, String tag) {
+def copyData() {
+  sh "mkdir -p $WORKSPACE/output"
+  sh 'cp -rf /var/jenkins_home/db/. $WORKSPACE/src'
+}
+
+def dockerRemove() {
+  echo '::: Remove image ************************************************************'
+  
+  // remove image
+  sh """        
+  # > /dev/null 2>&1 = Discards both the standard output and standard error of a command
+  # docker rmi database-changelog:1.0 > /dev/null 2>&1 && echo "image removed" || true
+
+  # 2>/dev/null = Discard standard error of a command
+  docker rmi database-changelog:1.0 2>/dev/null && echo "image removed" || { echo "image not found"; true; }
+  """
+}
+
+def dockerBuild() {
+  echo '::: Build image ************************************************************'
+  
+  // run shell script for building an image
+  sh '''
+  cp -r /dockerfiles/. $WORKSPACE/dockerfiles
+
+  cd dockerfiles/build
+  
+  ./build-database-changelog.sh
+
+  cd $WORKSPACE
+  '''
+}
+
+def runDocker(String command, String dbEnv, String dbName, boolean dryRun, String tag) {
 
   echo ">>>> $dbEnv"
-
-  def command = "rollback-tag"
-
-  if(dryRun) {
-    command = "rollback-tag-dryrun"
-  }
 
   def argsName1 = "--tag"
   def argsValue1 = "$tag"
@@ -29,11 +56,9 @@ pipeline {
   }
   parameters {
     choice(name: 'DB_ENV', choices:['SIT', 'UAT'])
-    string(name: 'DATABASE_NAME', defaultValue: 'database_b', description: 'Specific the database name\nr.g., database_b')
-    // choice(name: 'TYPE', choices:['DDL', 'DML', 'SP'], description: 'DDL - Data Definition Language\nDML - Data Manipulation Language\nSP - Stored Procedure')
-    // string(name: 'PROJECT_PATH', defaultValue: 'project_name_xyz/card-1', description: 'Specific the project path that you want to update\ne.g., <project-name>\ne.g., <project-name>-<card-number>')
+    string(name: 'DATABASE_NAME', defaultValue: 'database_b', description: 'Specific the database name\ne.g., database_b')
     booleanParam(name: 'DRY_RUN', defaultValue: true, description: 'Preview sql script before running migration')
-    string(name: 'TAG_VERSION', defaultValue: '2.0.0', description: 'The tag version which is revert a changesets\ne.g., 1.0.0\ne.g., release_1.0')
+    string(name: 'TAG_VERSION', defaultValue: '2.0.0', description: 'Specific a tag version that revert a changesets\ne.g., 1.0.0\ne.g., release_1.0')
   }
   stages {
     stage('Init') {
@@ -56,39 +81,37 @@ pipeline {
           }
         }
 
+        copyData()
+        dockerRemove()
+        dockerBuild()
+
       }
     }
-    stage('Rollback tag') {
+    stage('Dry run') {
+      when {
+        expression {
+          params.DRY_RUN == true
+        }
+      }
+      steps {
+        sh 'echo "Dry run"'
+
+        echo '::: Call runDocker() ************************************************************'
+        runDocker("rollback-tag-dryrun", params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.DRY_RUN, params.TAG_VERSION)
+        echo '::: ============================================================================='
+      }
+    }
+    stage('Rollback by tag version') {
+      when {
+        expression {
+          params.DRY_RUN == false
+        }
+      }
       steps {
         echo '::: Rollback tag ************************************************************'
 
-        sh "mkdir -p $WORKSPACE/output"
-        sh 'cp -rf /var/jenkins_home/db/. $WORKSPACE/src'        
-
-        echo '::: Remove image ************************************************************'
-        // remove image
-        sh """        
-        # > /dev/null 2>&1 = Discards both the standard output and standard error of a command
-        # docker rmi database-changelog:1.0 > /dev/null 2>&1 && echo "image removed" || true
-
-        # 2>/dev/null = Discard standard error of a command
-        docker rmi database-changelog:1.0 2>/dev/null && echo "image removed" || { echo "image not found"; true; }
-        """
-
-        echo '::: Build image ************************************************************'
-        // run shell script for building an image
-        sh '''
-        cp -r /dockerfiles/. $WORKSPACE/dockerfiles
-
-        cd dockerfiles/build
-        
-        ./build-database-changelog.sh
-
-        cd $WORKSPACE
-        '''
-
         echo '::: Call runDocker() ************************************************************'
-        runDocker(params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.DRY_RUN, params.TAG_VERSION)
+        runDocker("rollback-tag", params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.DRY_RUN, params.TAG_VERSION)
         echo '::: ============================================================================='
       }
     }
diff --git a/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-tag b/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-tag
--- a/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-tag
+++ b/deployment/jenkins/Jenkinsfile/database-changelog/Jenkinsfile-tag
@@ -1,8 +1,39 @@
-def runDocker(String dbEnv, String dbName, boolean checkVersion, String tag) {
+def copyData() {
+  sh "mkdir -p $WORKSPACE/output"
+  sh 'cp -rf /var/jenkins_home/db/. $WORKSPACE/src'
+}
+
+def dockerRemove() {
+  echo '::: Remove image ************************************************************'
+  
+  // remove image
+  sh """        
+  # > /dev/null 2>&1 = Discards both the standard output and standard error of a command
+  # docker rmi database-changelog:1.0 > /dev/null 2>&1 && echo "image removed" || true
+
+  # 2>/dev/null = Discard standard error of a command
+  docker rmi database-changelog:1.0 2>/dev/null && echo "image removed" || { echo "image not found"; true; }
+  """
+}
+
+def dockerBuild() {
+  echo '::: Build image ************************************************************'
+  
+  // run shell script for building an image
+  sh '''
+  cp -r /dockerfiles/. $WORKSPACE/dockerfiles
+
+  cd dockerfiles/build
+  
+  ./build-database-changelog.sh
+
+  cd $WORKSPACE
+  '''
+}
+
+def runDocker(String command, String dbEnv, String dbName, boolean checkVersion, String tag) {
 
   echo ">>>> $dbEnv"
-
-  def command = "tag"
 
   def argsName1 = "--tag"
   def argsValue1 = "$tag"
@@ -33,10 +64,10 @@ pipeline {
   }
   parameters {
     choice(name: 'DB_ENV', choices:['SIT', 'UAT'])
-    string(name: 'DATABASE_NAME', defaultValue: 'database_b', description: 'Specific the database name\nr.g., database_b')
+    string(name: 'DATABASE_NAME', defaultValue: 'database_b', description: 'Specific the database name\ne.g., database_b')
     // choice(name: 'TYPE', choices:['DDL', 'DML', 'SP'], description: 'DDL - Data Definition Language\nDML - Data Manipulation Language\nSP - Stored Procedure')
-    string(name: 'TAG_VERSION', defaultValue: '2.0.0', description: 'The tag version which is revert a changesets\ne.g., 1.0.0\ne.g., release_1.0')
-    booleanParam(name: 'CHECK_TAG_VERSION', defaultValue: true, description: 'Only check for tag existence')
+    string(name: 'TAG_VERSION', defaultValue: '2.0.0', description: 'Specific a tag version that changeset will be tagged\ne.g., 1.0.0\ne.g., release_1.0')
+    booleanParam(name: 'CHECK_TAG_VERSION_EXIST', defaultValue: true, description: 'Only check for tag existence')
   }
   stages {
     stage('Init') {
@@ -59,39 +90,18 @@ pipeline {
           }
         }
 
+        copyData()
+        dockerRemove()
+        dockerBuild()
+
       }
     }
     stage('Tag change log') {
       steps {
         echo '::: Tag change log ************************************************************'
-
-        sh "mkdir -p $WORKSPACE/output"
-        sh 'cp -rf /var/jenkins_home/db/. $WORKSPACE/src'        
-
-        echo '::: Remove image ************************************************************'
-        // remove image
-        sh """        
-        # > /dev/null 2>&1 = Discards both the standard output and standard error of a command
-        # docker rmi database-changelog:1.0 > /dev/null 2>&1 && echo "image removed" || true
-
-        # 2>/dev/null = Discard standard error of a command
-        docker rmi database-changelog:1.0 2>/dev/null && echo "image removed" || { echo "image not found"; true; }
-        """
-
-        echo '::: Build image ************************************************************'
-        // run shell script for building an image
-        sh '''
-        cp -r /dockerfiles/. $WORKSPACE/dockerfiles
-
-        cd dockerfiles/build
-        
-        ./build-database-changelog.sh
-
-        cd $WORKSPACE
-        '''
-
+  
         echo '::: Call runDocker() ************************************************************'
-        runDocker(params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.CHECK_TAG_VERSION, params.TAG_VERSION)
+        runDocker("tag", params.DB_ENV.toLowerCase(), params.DATABASE_NAME, params.CHECK_TAG_VERSION_EXIST, params.TAG_VERSION)
         echo '::: ============================================================================='
       }
     }
